version: "3"
services:
  sync:
    build: .
    pull_policy: build
    container_name: sync
    restart: unless-stopped
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DISPLAY=${DISPLAY}
      - VNC_PASSWORD=${VNC_PASSWORD}
    labels:
      - homepage.group=Automation
      - homepage.name=Sync
      - homepage.icon=https://www.sync.com/assets-meta/favicon-32x32.png
      - homepage.href=http://sync.${DOMAIN_NAME}/vnc.html
      - homepage.description=Sync.com files client
      - homepage.weight=5
      - traefik.enable=true
      - traefik.http.routers.sync.entrypoints=web,websecure
      - traefik.http.routers.sync.rule=Host(`sync.${DOMAIN_NAME}`)
      - traefik.http.routers.sync.tls=true
      - traefik.http.routers.sync.tls.certresolver=myresolver
      - "com.centurylinklabs.watchtower.enable=false"

    volumes:
      - synccom_data:/root/.wine
      - ${DATA_ROOT}/Sync:/root/.wine/drive_c/users/root/Sync
    networks:
      - web
volumes:
  synccom_data:
networks:
  web:
    external: true
